/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String =
        "androidx.test.espresso:espresso-core:" + Versions.espresso_core

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test_runner

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit

    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    const val multidex = "androidx.multidex:multidex:" + Versions.multidex

    // room
    const val room = "androidx.room:room-runtime:" + Versions.room

    // optional - Kotlin Extensions and Coroutines support for Room
    const val room_ktx = "androidx.room:room-ktx:" + Versions.room

    const val material = "com.google.android.material:material:" + Versions.google_material

    const val lifecycle_extensions = "androidx.lifecycle:lifecycle-extensions:" + Versions.lifecycle

    // annotationProcessor "androidx.lifecycle:lifecycle-compiler:${arch.lifecycle}"
    const val livedata = "androidx.lifecycle:lifecycle-livedata-ktx:" + Versions.livedata
    const val lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:" + Versions.lifecycle

    const val lifecycle_viewmodel =
        "androidx.lifecycle:lifecycle-viewmodel-ktx:" + Versions.lifecycle

    const val work_runtime_ktx = "androidx.work:work-runtime-ktx:" + Versions.work_version

    // RETROFIT
    const val retrofit = "com.squareup.retrofit2:retrofit:" + Versions.retrofit
    const val retrofit_converter_moshi =
        "com.squareup.retrofit2:converter-moshi:" + Versions.retrofit
    const val logging_interceptor =
        "com.squareup.okhttp3:logging-interceptor:" + Versions.logging_interceptor

    // moshi
    const val moshi = "com.squareup.moshi:moshi-kotlin:" + Versions.moshi

    // joda time
    const val joda_time = "net.danlew:android.joda:" + Versions.joda_time

    const val kapt_room: String = "androidx.room:room-compiler:" + Versions.room

    const val kapt_moshi_codegen: String =
        "com.squareup.moshi:moshi-kotlin-codegen:" + Versions.moshi
    const val cardview = "androidx.cardview:cardview:" + Versions.cardview

    const val navigation_fragment =
        "androidx.navigation:navigation-fragment-ktx:" + Versions.nav_version

    const val navigation_ui = "androidx.navigation:navigation-ui-ktx:" + Versions.nav_version

    const val androix_annotation = "androidx.annotation:annotation:" + Versions.appcompat

    const val tempo = "com.github.AllanHasegawa.Tempo:tempo:" + Versions.tempo

    const val gson = "com.google.code.gson:gson:" + Versions.gson

    const val mockk = "io.mockk:mockk:" + Versions.mockk

    const val swipe_refresh_layout =
        "androidx.swiperefreshlayout:swiperefreshlayout:" + Versions.swipe_refresh_layout

    const val koin_android_viewmodel = "org.koin:koin-androidx-viewmodel:" + Versions.koin_android

    const val kotlin_logging = "io.github.microutils:kotlin-logging:" + Versions.kotlin_logging

    const val recycler_view_swipe =
        "com.github.xabaras:RecyclerViewSwipeDecorator:" + Versions.recycler_view_swipe

}
