import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val kotlin_logging = "1.7.8"
    const val koin_android = "2.1.0"
    const val swipe_refresh_layout = "1.0.0"
    const val mockk = "1.9.3"
    const val gson = "2.8.6"
    const val tempo = "0.2.0"
    const val cardview = "1.0.0"
    const val apache_commons = "1.6"
    const val arc_layout = "1.0.3"
    const val joda_time: String = "2.10.2"
    const val google_material: String = "1.1.0"
    const val appcompat: String = "1.1.0"
    const val constraintlayout: String = "2.0.0-beta4"
    const val core_ktx: String = "1.1.0"
    const val espresso_core: String = "3.2.0"
    const val androidx_test_runner: String = "1.2.0"
    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2" // available: "0.5.0"
    const val junit: String = "4.12"
    const val org_jetbrains_kotlin: String = "1.3.72" // available: "1.3.50"

    /**
     *
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val multidex: String = "2.0.1"

    /**
     *
     * Project libraries
     */

    const val retrofit: String = "2.6.1"
    const val logging_interceptor: String = "3.8.0"
    const val firebase: String = "17.3.3" //11.0.2
    const val google: String = "17.0.0" //10.2.6
    const val crashlytics: String = "2.5.1"
    const val ahbottomnavigation: String = "2.3.4"
    const val circleprogress: String = "1.2.1"
    const val work_version: String = "2.2.0"
    const val nav_version: String = "2.1.0"
    const val moshi: String = "1.8.0"

    // ARCHITECTURE
    const val room: String = "2.2.0-rc01"
    const val lifecycle: String = "2.2.0"
    const val livedata: String = "2.2.0-rc02"

    const val carousel_view = "0.1.5"

    const val recycler_view_swipe = "1.4"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
        id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
